import type { Locale, UiCopy } from './types';

export const uiCopy: Record<Locale, UiCopy> = {
  'zh-CN': {
    localeName: '简体中文',
    shortLocale: '中',
    skipLink: '跳到主要内容',
    brandAria: '当归首页',
    metaDescription: '把计划、提醒、行动、过往与笔记连成一条安静的本地工作流。',
    nav: {
      features: '功能', stories: '故事', download: '获取', privacy: '隐私', support: '支持', github: 'GitHub',
      menu: '菜单', language: '切换语言',
    },
    common: {
      preRelease: '公开预发布', stableRelease: '稳定版', currentPublicRelease: '当前公开版本',
      releaseUnavailable: '版本信息暂时不可用', publishedOn: '发布于', readStory: '读这个故事',
      viewAllStories: '看全部八篇故事', backToStories: '返回故事', previousStory: '上一篇',
      nextStory: '下一篇', openNewWindow: '在新窗口打开',
    },
    home: {
      promise: '本地记录 · 不上传 · 不调用 AI',
      primaryCta: '获取当前公开版本', secondaryCta: '看看真实界面',
      releaseNote: 'Android 稳定版可安装 · iOS 仅提供源码 · 发布状态自动跟随 GitHub Release',
      previewEyebrow: '真实工作流，不是设计稿', previewTitle: '从今天，到可以回看的过往',
      previewDescription: '计划、提醒、行动、过往与笔记，在一张安静的暖纸上自然接续。',
      previewAlt: '当归真实应用工作流界面', showcaseCapture: '真实界面示例 · 截图于 v1.1.5',
      showcaseItems: [
        { title: '计划，落到今天', body: '从小球与幼苗开始，把想法变成今天可以行动的一步。' },
        { title: '完成，不等于消失', body: '完成不是清空：行动会沉淀为可以继续编辑的过往。' },
        { title: '写下，也带得走', body: '笔记留下思考，可读导出让数据真正归你。' },
      ],
      featuresEyebrow: '三件重要的小事', featuresTitle: '帮你记住，但不接管你的生活',
      storiesEyebrow: '小当归的纸上花园', storiesTitle: '五张纸页，一次安静的翻阅',
      storiesDescription: '把鼠标、焦点或手指移到一张纸页上，它会来到最前面；完整的八篇故事仍各有自己的页面。',
      privacyEyebrow: '工具应当安静地属于你', privacyTitle: '你的内容，不是我们的原料',
      privacyDescription: '当归不需要账号，不接入广告、分析或远程 AI；记录只在本机和你主动选择的备份位置。',
      privacyPoints: ['无账号', '无内容上传', '无广告与分析', 'Android 无 INTERNET 权限'],
      downloadEyebrow: '获取当归', downloadTitle: '公开版本只从发布通道生长',
      downloadDescription: '官网只读取已公开且附件完整的 GitHub Release。开发分支、普通标签和草稿不会出现在这里。',
      androidCta: '查看 Android 获取方式', iosCta: '了解 iOS 源码构建',
      sectionNav: {
        label: '本页章节', show: '显示本页导航', hide: '隐藏本页导航',
        items: { top: '开始', preview: '真实界面', features: '功能', stories: '故事', privacy: '隐私', download: '获取' },
      },
    },
    stories: {
      eyebrow: '纸上花园', title: '小当归的八个故事',
      intro: '它们不是功能说明的替代品，而是另一种理解“本地、安静、仍可编辑”的方式。',
      detailEyebrow: '小当归的故事', relatedTitle: '纸页还在继续',
    },
    download: {
      eyebrow: '获取当归', title: '下载之前，先看清当前公开版本',
      intro: '版本号、状态、日期和附件由已公开的 GitHub Release 自动提供；开发中的版本不会提前出现。',
      androidTitle: 'Android',
      androidBody: '普通用户请使用正式签名的通用 Release APK。分架构 APK 和 AAB 属于开发者资产，不适合日常安装。',
      androidRecommended: '推荐文件：danggui-android-universal-release.apk',
      releaseCta: '查看完整发布说明', androidCta: '下载通用 Android APK',
      checksumTitle: '安装前核对',
      checksumBody: '发布通道同时提供 SHA256SUMS 与签名证书指纹。不要安装来源不明或标记为 debug-fallback 的文件。',
      checksumCta: '下载 SHA256SUMS', iosTitle: 'iOS', sourceLabel: '源码',
      iosBody: '当前只交付完整源码、Xcode 工程和无签名构建证据。真机运行需要你自己的 Apple 签名身份与描述文件。',
      iosWarning: '不是 IPA，也没有 TestFlight；源码压缩包不能直接安装到普通 iPhone。',
      iosCta: '下载当前 iOS 源码', iosGuideCta: '阅读 iOS 源码构建说明',
      previewAvailable: '另有较新的公开预发布版', previewCta: '查看预发布版', allReleasesCta: '查看所有公开版本',
      releaseHighlightsEyebrow: 'v1.1.5 稳定版',
      releaseHighlightsTitle: '让可靠性安静地长在底层',
      releaseHighlightsIntro: '这一版没有把复杂性推给你，而是把提醒、时区、数据库与恢复流程之间容易出错的缝隙补得更严密。',
      releaseHighlights: [
        { title: '旧操作不越过新编辑', body: '过期通知中的停止或稍后提醒，不再改动后来编辑过的新提醒。' },
        { title: '提醒记得自己的时区', body: '初次排期及 10、30、60 分钟稍后提醒会保留原本时区，并正确跨过夏令时切换。' },
        { title: '恢复前先把数据库看完整', body: '启动和恢复会执行完整的数据库完整性与结构检查，异常内容不会提前进入日常写入。' },
        { title: '失败也留下清楚边界', body: '缺失提醒采用有时限、可追溯的保守恢复；分享和恢复产生的临时明文会按明确目录清理。' },
      ],
      evidenceTitle: '验证边界',
      evidenceBody: '稳定版表示它是当前推荐发布通道，不代表所有设备场景都已完成实机验证。Android API 24/36 与 iOS 18.5/26.5 Simulator 自动化已经通过；iOS 仍只交付源码，没有 IPA 或 TestFlight。真实设备长期后台、部分 OEM 和突然断电场景仍以发行说明为准。',
      beforeTitle: '开始前',
      beforeItems: ['重要数据先在应用内创建 .dgbak 备份。', '确认当前版本仍符合你的风险预期。', '遇到问题时不要在 Issue 中上传真实笔记、备份或密码。'],
    },
    privacy: {
      eyebrow: '隐私承诺', proofEyebrow: '开源 · 公开审计', title: '记录留在设备里，边界写在明处',
      intro: '当归是一款完全本地的事项与笔记应用。它不要求你先把生活交给一个账号，才允许你开始记录。',
      principles: [
        { title: '不创建账号', body: '应用没有登录、用户画像或业务服务器；打开就可以离线使用。' },
        { title: '不上传内容', body: '事项、过往与笔记保存在应用沙箱和你主动选择的本地备份位置。' },
        { title: '不调用 AI', body: '应用不会把文字发送给任何 AI。只有你主动导出后，才由你决定如何使用文件。' },
        { title: '不做追踪', body: '不集成广告、分析、崩溃遥测、Firebase 或用户追踪 SDK。' },
      ],
      policyEyebrow: '正式政策', policyTitle: '数据如何留存、移动与删除', policyUpdated: '生效日期：2026 年 8 月 26 日',
      controllerTitle: '政策主体与联系',
      controllerBody: '本政策由“当归项目维护者”提供。如需询问隐私或数据边界，请通过页面底部的支持邮箱联系。',
      policySections: [
        { title: '设备内的本地数据', body: '事项、提醒、过往、笔记与设置保存在设备上的本地数据库和应用沙箱中。项目维护者没有业务服务器可以读取这些内容。' },
        { title: '权限、导出与删除', body: '提醒功能只在需要时请求系统通知权限。备份与可读导出仅在你主动操作时生成到你选择的位置；你可以在应用中删除记录，也可以卸载应用并自行删除已导出的文件。' },
        { title: '不会发生的处理', body: '应用不创建账号，不把内容保存到项目云端，不接入广告、访问分析、崩溃遥测或远程 AI，也不会自动上传你的记录。' },
        { title: '支持邮件', body: '你主动发送的邮箱地址与邮件内容只用于理解和回复请求，并在请求解决及必要的安全保留期限结束后删除。请勿在邮件中发送真实笔记、备份、密码、证书或其他私密内容。' },
        { title: '网站与外部链接', body: '本站不设账号、表单或访客分析。Cloudflare 为传输、安全和站点运行处理必要连接元数据，例如 IP 地址、请求时间、网址和浏览器信息；前往 GitHub 后，相关处理适用 GitHub 自身的隐私政策。' },
      ],
      proofTitle: '承诺之外，还有可以检查的证据',
      proofBody: 'Android 正式清单不声明 INTERNET 权限；iOS 没有推送、CloudKit、后台网络或联网能力。生产依赖与平台配置均有公开审计记录。',
      proofCta: '查看当前版本的隐私审计', siteTitle: '关于这个网站',
      siteBody: '网站服务器只读取公开发布清单，无法接触你在当归中的记录。隐私问题或数据请求可以直接联系项目维护者。',
      contactCta: '发送隐私邮件',
    },
    support: {
      eyebrow: '用户支持', title: '需要时，沿着纸页找回来',
      intro: '先从下面的常见问题开始；仍未解决时，可以通过邮件或 GitHub Issues 联系项目维护者。',
      contactEyebrow: '直接联系', contactTitle: '把问题说清楚，不必交出你的内容',
      contactBody: '请说明设备型号、系统版本、当归版本、复现步骤和你看到的提示。通常不需要附上任何真实数据。',
      emailCta: '发送支持邮件', issuesCta: '打开 GitHub Issues', downloadCta: '查看当前公开版本',
      warningTitle: '发送之前',
      warningBody: '请勿通过邮件或公开 Issue 发送真实事项、笔记、数据库、备份、密码、证书、密钥或其他个人信息。必要时请只提供脱敏后的示例。',
      faqEyebrow: '常见问题', faqTitle: '先自己排查这 6 件事',
      faqs: [
        { question: '在哪里查看当归版本号？', answer: '打开“设置 → 关于当归”即可看到已安装版本。官网“获取”页显示当前公开版本、发布状态与校验文件；开发中的版本不会提前出现。' },
        { question: '怎样备份、恢复或导出？', answer: '前往“设置 → 数据与备份”。完整恢复请使用 .dgbak 备份；长期阅读或迁移可生成包含 Markdown 与 JSON 的可读 ZIP。恢复前会先备份当前数据，请只使用可信文件。' },
        { question: '提醒没有响，先检查什么？', answer: '先查看事项卡片上的提醒状态，再确认系统通知、声音与振动已开启。Android 还需检查精确提醒权限和设备省电限制；iOS 的声音与振动由系统通知设置控制。' },
        { question: 'iPhone 需要什么系统？', answer: '当前源码构建要求 iOS 15 或更高版本，并需要你自己的 Apple 签名身份与描述文件。' },
        { question: 'Android 当前是稳定版吗？', answer: '是。v1.1.5 是当前推荐的稳定版，提供正式签名的 Android 7.0+ 通用 APK。安装或升级前仍建议阅读发布说明、核对 SHA256SUMS，并先备份重要数据。' },
        { question: '什么时候能直接安装 iPhone 版本？', answer: 'iPhone 版本正在准备中。目前没有 App Store、TestFlight 或可直接安装的 IPA；可用状态会以官网“获取”页和公开 Release 为准。' },
      ],
    },
    footer: {
      tagline: '本地记录 · 不上传 · 不调用 AI', source: '源代码', license: 'Apache 2.0',
      trademark: '品牌与商标', status: '当前公开版本',
    },
  },
  en: {
    localeName: 'English', shortLocale: 'EN', skipLink: 'Skip to main content', brandAria: '当归 home',
    metaDescription: 'A quiet local workflow connecting plans, reminders, actions, Past, and Notes.',
    nav: { features: 'Features', stories: 'Stories', download: 'Get the app', privacy: 'Privacy', support: 'Support', github: 'GitHub', menu: 'Menu', language: 'Change language' },
    common: {
      preRelease: 'Public pre-release', stableRelease: 'Stable release', currentPublicRelease: 'Current public release',
      releaseUnavailable: 'Release details are temporarily unavailable', publishedOn: 'Published', readStory: 'Read this story',
      viewAllStories: 'Read all eight stories', backToStories: 'Back to stories', previousStory: 'Previous', nextStory: 'Next',
      openNewWindow: 'Opens in a new window',
    },
    home: {
      promise: 'Local records · No uploads · No AI', primaryCta: 'Get the current public release', secondaryCta: 'See the real app',
      releaseNote: 'Stable Android installer · iOS source only · Status follows published GitHub Releases',
      previewEyebrow: 'A real workflow, not a mockup', previewTitle: 'From today to a Past you can revisit',
      previewDescription: 'Plans, reminders, actions, Past, and Notes continue naturally across one quiet sheet of warm paper.',
      previewAlt: 'Real 当归 application workflow', showcaseCapture: 'Real interface example · Captured in v1.1.5',
      showcaseItems: [
        { title: 'Bring a plan into today', body: 'Start with the orb and seedling, then turn an idea into one step you can take today.' },
        { title: 'Done does not mean gone', body: 'Completion is not deletion: actions settle into an editable Past.' },
        { title: 'Write it down, take it with you', body: 'Notes keep your thinking; readable exports keep your data truly yours.' },
      ],
      featuresEyebrow: 'Three things that matter', featuresTitle: 'Helps you remember without taking over',
      storiesEyebrow: '小当归 (Little Danggui) and the paper garden', storiesTitle: 'Five paper pages, one quiet browse',
      storiesDescription: 'Move a pointer, focus, or tap a page and it comes forward. All eight complete stories still have their own pages.',
      privacyEyebrow: 'A tool should quietly belong to you', privacyTitle: 'Your words are not our raw material',
      privacyDescription: '当归 needs no account and includes no ads, analytics, or remote AI. Records stay on your device and in backups you choose.',
      privacyPoints: ['No account', 'No content uploads', 'No ads or analytics', 'No Android INTERNET permission'],
      downloadEyebrow: 'Get 当归', downloadTitle: 'Public releases grow through one trusted channel',
      downloadDescription: 'The site accepts only published GitHub Releases with a complete asset set. Branches, tags alone, and drafts stay invisible.',
      androidCta: 'See Android options', iosCta: 'Read the iOS source guide',
      sectionNav: { label: 'On this page', show: 'Show page navigation', hide: 'Hide page navigation', items: { top: 'Start', preview: 'Real app', features: 'Features', stories: 'Stories', privacy: 'Privacy', download: 'Get it' } },
    },
    stories: { eyebrow: 'The paper garden', title: 'Eight stories from 小当归', intro: 'They do not replace feature documentation. They are another way to understand local, quiet, and still editable.', detailEyebrow: 'A 小当归 story', relatedTitle: 'The paper continues' },
    download: {
      eyebrow: 'Get 当归', title: 'Know the current public release before downloading',
      intro: 'Version, channel, date, and files come automatically from a published GitHub Release. Work in progress never appears early.',
      androidTitle: 'Android', androidBody: 'Most people should use the formally signed universal Release APK. Split APKs and the AAB are developer assets, not everyday installers.',
      androidRecommended: 'Recommended: danggui-android-universal-release.apk', releaseCta: 'Read the full release notes', androidCta: 'Download the universal Android APK',
      checksumTitle: 'Verify before installing', checksumBody: 'The channel includes SHA256SUMS and the signing-certificate fingerprint. Do not install unknown or debug-fallback files.', checksumCta: 'Download SHA256SUMS',
      iosTitle: 'iOS', sourceLabel: 'Source', iosBody: 'iOS is delivered as complete source, an Xcode project, and unsigned build evidence. A device build requires your own Apple identity and profile.',
      iosWarning: 'This is not an IPA and there is no TestFlight build. The source archive cannot be installed directly on a regular iPhone.',
      iosCta: 'Download the current iOS source', iosGuideCta: 'Read the iOS source build guide',
      previewAvailable: 'A newer public preview is also available', previewCta: 'View the preview', allReleasesCta: 'View every public release', beforeTitle: 'Before you begin',
      releaseHighlightsEyebrow: 'v1.1.5 stable release',
      releaseHighlightsTitle: 'Quiet reliability, strengthened underneath',
      releaseHighlightsIntro: 'This release closes gaps between reminders, time zones, database integrity, and recovery without pushing that complexity into your daily workflow.',
      releaseHighlights: [
        { title: 'Old actions cannot cross a new edit', body: 'Stop or Snooze from a stale notification can no longer modify a reminder that was edited afterward.' },
        { title: 'Reminders keep their time zone', body: 'Initial scheduling and 10, 30, or 60-minute Snooze preserve the intended time zone across daylight-saving changes.' },
        { title: 'The database is checked in full', body: 'Startup and restore perform complete integrity and schema checks before unusual content can reach everyday writes.' },
        { title: 'Failure keeps an honest boundary', body: 'Missing reminders use bounded, auditable recovery, while temporary plaintext from sharing and restore is cleaned from exact locations.' },
      ],
      evidenceTitle: 'Evidence boundary',
      evidenceBody: 'Stable means this is the recommended release channel; it does not imply every device scenario has been tested. Automation passed on Android API 24/36 and iOS 18.5/26.5 Simulators. iOS remains source-only, with no IPA or TestFlight build. Long-lived physical-device delivery, some OEM behavior, and sudden power loss remain bounded by the release notes.',
      beforeItems: ['Create a .dgbak backup before upgrading important data.', 'Confirm the current channel matches your risk tolerance.', 'Never attach real notes, backups, or passwords to a public issue.'],
    },
    privacy: {
      eyebrow: 'Privacy promise', proofEyebrow: 'Open source · Public audit', title: 'Your records stay on-device. The boundary stays visible.',
      intro: '当归 is a fully local Tasks and Notes app. It does not make you hand your life to an account before you can begin.',
      principles: [
        { title: 'No account', body: 'There is no login, user profile, or application server. Open the app and work offline.' },
        { title: 'No uploads', body: 'Tasks, Past, and Notes stay in the app sandbox and local backup locations you actively choose.' },
        { title: 'No AI calls', body: 'The app sends no text to AI. Only an export you make can be used elsewhere, under your control.' },
        { title: 'No tracking', body: 'There are no ads, analytics, crash telemetry, Firebase, or user-tracking SDKs.' },
      ],
      policyEyebrow: 'Formal policy', policyTitle: 'How data stays, moves, and is deleted', policyUpdated: 'Effective date: August 26, 2026',
      controllerTitle: 'Who provides this policy',
      controllerBody: 'This policy is provided by the 当归 project maintainer. For privacy questions or data-boundary concerns, use the support email at the end of this page.',
      policySections: [
        { title: 'Local data on your device', body: 'Tasks, reminders, Past, Notes, and settings live in a local database and the app sandbox on your device. The project maintainer has no application server that can read this content.' },
        { title: 'Permissions, exports, and deletion', body: 'Reminders request system notification permission only when needed. Backups and readable exports are created only when you choose a destination. You can delete records in the app, uninstall the app, and delete exported files yourself.' },
        { title: 'Processing that does not happen', body: 'The app creates no account, stores no content in a project cloud, and includes no advertising, visitor analytics, crash telemetry, remote AI, or automatic record uploads.' },
        { title: 'Support email', body: 'An email address and message you send are used only to understand and answer your request. They are deleted after the request is resolved and any necessary security-retention period ends. Never email real notes, backups, passwords, certificates, or other private content.' },
        { title: 'Website and external links', body: 'This site has no account, forms, or visitor analytics. Cloudflare processes necessary connection metadata, such as IP address, request time, URL, and browser information, to deliver, secure, and operate the site. GitHub applies its own privacy policy after you follow an external GitHub link.' },
      ],
      proofTitle: 'The promise has inspectable evidence', proofBody: 'The final Android manifest declares no INTERNET permission. iOS has no push, CloudKit, background-network, or networking capability. Production dependencies and platform settings are publicly audited.',
      proofCta: 'Read the current privacy audit', siteTitle: 'About this website',
      siteBody: 'The site server reads only a public release manifest and cannot access anything you write in 当归. Contact the project maintainer for a privacy question or data request.',
      contactCta: 'Email a privacy question',
    },
    support: {
      eyebrow: 'User support', title: 'Find your way back when something feels stuck',
      intro: 'Start with the common questions below. If the answer is not there, contact the project maintainer by email or GitHub Issues.',
      contactEyebrow: 'Contact', contactTitle: 'Describe the problem without sharing your content',
      contactBody: 'Include your device model, operating-system version, 当归 version, steps to reproduce, and the message you see. Real user data is almost never needed.',
      emailCta: 'Email support', issuesCta: 'Open GitHub Issues', downloadCta: 'View the current public release',
      warningTitle: 'Before you send',
      warningBody: 'Never send real tasks, notes, databases, backups, passwords, certificates, keys, or other personal information by email or in a public issue. Use a redacted example if one is necessary.',
      faqEyebrow: 'Common questions', faqTitle: 'Check these 6 things first',
      faqs: [
        { question: 'Where can I find the 当归 version?', answer: 'Open Settings → About 当归 to see the installed version. The website’s Get the app page shows the current public release, channel, and checksum files. Work in progress does not appear early.' },
        { question: 'How do backup, restore, and export differ?', answer: 'Open Settings → Data & Backup. Use a .dgbak backup for a complete restore. Create a readable ZIP with Markdown and JSON for long-term reading or migration. 当归 backs up current data before a restore; use only trusted files.' },
        { question: 'What should I check when a reminder does not sound?', answer: 'Check the reminder status on the task card, then confirm system notifications, sound, and vibration are enabled. On Android, also review exact-reminder permission and battery restrictions. On iOS, system notification settings control sound and vibration.' },
        { question: 'Which iOS version is required?', answer: 'The current source build requires iOS 15 or later, plus your own Apple signing identity and provisioning profile.' },
        { question: 'Is the Android build stable?', answer: 'Yes. v1.1.5 is the current recommended stable release and includes a formally signed universal APK for Android 7.0+. Read the release notes, verify SHA256SUMS, and back up important data before installing or upgrading.' },
        { question: 'When can I install 当归 on an iPhone?', answer: 'The iPhone release is in preparation. There is no App Store listing, TestFlight build, or directly installable IPA yet. The Get the app page and published Releases are the source of truth.' },
      ],
    },
    footer: { tagline: 'Local records · No uploads · No AI', source: 'Source code', license: 'Apache 2.0', trademark: 'Brand & trademarks', status: 'Current public release' },
  },
  ja: {
    localeName: '日本語', shortLocale: '日', skipLink: 'メインコンテンツへ移動', brandAria: '当归ホーム',
    metaDescription: '計画、通知、行動、過往、ノートを静かなローカルの流れにつなぐアプリ。',
    nav: { features: '特長', stories: '物語', download: '入手', privacy: 'プライバシー', support: 'サポート', github: 'GitHub', menu: 'メニュー', language: '言語を変更' },
    common: {
      preRelease: '公開プレリリース', stableRelease: '安定版', currentPublicRelease: '現在の公開版', releaseUnavailable: '版情報を一時的に取得できません',
      publishedOn: '公開日', readStory: 'この物語を読む', viewAllStories: '8つの物語をすべて読む', backToStories: '物語へ戻る',
      previousStory: '前の物語', nextStory: '次の物語', openNewWindow: '新しいウィンドウで開きます',
    },
    home: {
      promise: 'ローカル記録・アップロードなし・AI 不使用', primaryCta: '現在の公開版を入手', secondaryCta: '実際の画面を見る',
      releaseNote: 'Android 安定版をインストール可・iOS はソースのみ・状態は公開済み GitHub Release と同期',
      previewEyebrow: 'モックではなく、実際の流れ', previewTitle: '今日から、振り返れる過往へ',
      previewDescription: '計画、通知、行動、過往、ノートが、静かな暖紙の上で自然につながります。',
      previewAlt: '当归アプリの実際のワークフロー', showcaseCapture: '実画面の例・v1.1.5 で撮影',
      showcaseItems: [
        { title: '計画を今日へ', body: '小さな球と芽から始め、考えを今日できる一歩に変えます。' },
        { title: '完了は消去ではない', body: '完了した行動は、あとから編集できる過往として残ります。' },
        { title: '書いて、持ち出せる', body: 'ノートに考えを残し、読みやすい書き出しでデータを自分のものに。' },
      ],
      featuresEyebrow: '大切な三つのこと', featuresTitle: '覚える手助けはしても、暮らしを支配しない',
      storiesEyebrow: '小当归（ちいさなダングイ）の紙の庭', storiesTitle: '五枚の紙を、静かにめくる',
      storiesDescription: 'ポインター、フォーカス、タップで一枚が手前へ。8つの物語にはそれぞれ完全なページがあります。',
      privacyEyebrow: '道具は静かに、あなたのもの', privacyTitle: 'あなたの言葉を、私たちの材料にしない',
      privacyDescription: '当归にアカウントは不要です。広告、分析、外部 AI もありません。記録は端末と自分で選んだバックアップだけに残ります。',
      privacyPoints: ['アカウント不要', '内容をアップロードしない', '広告・分析なし', 'Android の INTERNET 権限なし'],
      downloadEyebrow: '当归を入手', downloadTitle: '公開版は一つの検証済み経路から',
      downloadDescription: '完全なファイルを持つ公開済み GitHub Release だけを表示します。開発ブランチ、タグのみ、下書きは表示されません。',
      androidCta: 'Android の入手方法', iosCta: 'iOS ソース構築ガイド',
      sectionNav: { label: 'このページ', show: 'ページナビを表示', hide: 'ページナビを隠す', items: { top: 'はじめ', preview: '実画面', features: '特長', stories: '物語', privacy: 'プライバシー', download: '入手' } },
    },
    stories: { eyebrow: '紙の庭', title: '小当归の八つの物語', intro: '機能説明の代わりではなく、「ローカルで、静かで、まだ編集できる」を別の角度から感じるための物語です。', detailEyebrow: '小当归の物語', relatedTitle: '紙はまだ続きます' },
    download: {
      eyebrow: '当归を入手', title: 'ダウンロード前に現在の公開版を確認', intro: '版、チャンネル、公開日、ファイルは公開済み GitHub Release から自動取得します。開発中の版は先に表示されません。',
      androidTitle: 'Android', androidBody: '通常は正式署名済み universal Release APK を使ってください。分割 APK と AAB は開発者向けです。',
      androidRecommended: '推奨：danggui-android-universal-release.apk', releaseCta: '完全なリリース説明を見る', androidCta: 'universal Android APK をダウンロード',
      checksumTitle: 'インストール前の確認', checksumBody: 'SHA256SUMS と署名証明書の指紋を確認できます。不明な出所や debug-fallback のファイルは使わないでください。', checksumCta: 'SHA256SUMS をダウンロード',
      iosTitle: 'iOS', sourceLabel: 'ソース', iosBody: 'iOS は完全なソース、Xcode プロジェクト、未署名ビルド証拠のみです。実機には自分の Apple 署名情報が必要です。',
      iosWarning: 'IPA ではなく、TestFlight もありません。ソース ZIP は通常の iPhone に直接インストールできません。',
      iosCta: '現在の iOS ソースをダウンロード', iosGuideCta: 'iOS ソースのビルド手順を読む',
      previewAvailable: 'より新しい公開プレビュー版もあります', previewCta: 'プレビュー版を見る', allReleasesCta: 'すべての公開版を見る', beforeTitle: '始める前に',
      releaseHighlightsEyebrow: 'v1.1.5 安定版',
      releaseHighlightsTitle: '静かな信頼性を、土台から',
      releaseHighlightsIntro: '通知、タイムゾーン、データベース、復元の間にある小さな隙間を埋め、日々の操作へ複雑さを持ち込みません。',
      releaseHighlights: [
        { title: '古い操作は新しい編集を越えない', body: '古い通知の停止やスヌーズが、後から編集した新しい通知へ影響しないようになりました。' },
        { title: '通知がタイムゾーンを覚えている', body: '初回設定と 10・30・60 分のスヌーズで元のタイムゾーンを保ち、夏時間の切り替えにも対応します。' },
        { title: '復元前に全体を確認する', body: '起動・復元時にデータベースの完全性とスキーマを厳密に検証し、異常な内容を通常の書き込みへ渡しません。' },
        { title: '失敗にも明確な境界を残す', body: '見つからない通知は期限付きで追跡可能な復旧を行い、共有・復元で生じた一時的な平文は決められた場所から削除します。' },
      ],
      evidenceTitle: '検証範囲',
      evidenceBody: '安定版とは現在の推奨チャンネルであることを示し、すべての実機場面を検証済みとするものではありません。Android API 24／36 と iOS 18.5／26.5 Simulator の自動化は通過しています。iOS は引き続きソースのみで、IPA と TestFlight はありません。実機の長時間バックグラウンド、一部 OEM、突然の電源断についてはリリース説明の境界が適用されます。',
      beforeItems: ['重要なデータは .dgbak でバックアップしてください。', '現在のチャンネルが許容できるリスクか確認してください。', '公開 Issue に実際のノート、バックアップ、パスワードを添付しないでください。'],
    },
    privacy: {
      eyebrow: 'プライバシーの約束', proofEyebrow: 'オープンソース・公開監査', title: '記録は端末に。境界は見えるところに。', intro: '当归は完全ローカルの事項・ノートアプリです。記録を始めるために暮らしをアカウントへ預ける必要はありません。',
      principles: [
        { title: 'アカウントなし', body: 'ログイン、ユーザープロファイル、業務サーバーはありません。開けばオフラインで使えます。' },
        { title: 'アップロードなし', body: '事項、過往、ノートはアプリ領域と、自分で選んだローカルバックアップ先に残ります。' },
        { title: 'AI 呼び出しなし', body: '文章を AI に送りません。自分で書き出したファイルの使い道は自分で決められます。' },
        { title: '追跡なし', body: '広告、分析、クラッシュ送信、Firebase、追跡 SDK はありません。' },
      ],
      policyEyebrow: '正式な方針', policyTitle: 'データの保存、移動、削除について', policyUpdated: '施行日：2026年8月26日',
      controllerTitle: '方針の提供者と連絡先',
      controllerBody: 'この方針は「当归プロジェクト管理者」が提供します。プライバシーやデータ境界については、ページ末尾のサポートメールからお問い合わせください。',
      policySections: [
        { title: '端末内のローカルデータ', body: '事項、通知、過往、ノート、設定は、端末内のローカルデータベースとアプリ領域に保存されます。プロジェクト管理者がその内容を読める業務サーバーはありません。' },
        { title: '権限、書き出し、削除', body: '通知は必要なときだけシステム権限を求めます。バックアップと読みやすい書き出しは、自分で保存先を選んだときだけ作成されます。記録はアプリ内で削除でき、アプリのアンインストールや書き出したファイルの削除も自分で行えます。' },
        { title: '行わない処理', body: 'アカウントを作らず、内容をプロジェクトのクラウドに保存しません。広告、アクセス解析、クラッシュ送信、外部 AI、自動アップロードもありません。' },
        { title: 'サポートメール', body: '送信されたメールアドレスと本文は、問い合わせの理解と返信にだけ使用します。解決後、必要な安全上の保管期間が終わり次第削除します。実際のノート、バックアップ、パスワード、証明書などは送らないでください。' },
        { title: 'ウェブサイトと外部リンク', body: 'このサイトにアカウント、フォーム、訪問者分析はありません。Cloudflare は配信、安全、運用に必要な接続情報（IP アドレス、リクエスト時刻、URL、ブラウザ情報など）を処理します。GitHub へ移動した後は GitHub 自身のプライバシーポリシーが適用されます。' },
      ],
      proofTitle: '約束は、確認できる証拠とともに', proofBody: 'Android の正式マニフェストに INTERNET 権限はありません。iOS に Push、CloudKit、バックグラウンド通信の権限もありません。依存関係と設定は公開監査されています。',
      proofCta: '現在のプライバシー監査を見る', siteTitle: 'このウェブサイトについて',
      siteBody: 'サイトのサーバーは公開リリース情報だけを読み、当归に書いた内容へアクセスできません。プライバシーに関する質問やデータの相談は、プロジェクト管理者へ直接連絡できます。',
      contactCta: 'プライバシーについてメールする',
    },
    support: {
      eyebrow: 'ユーザーサポート', title: '迷ったとき、静かに戻れる道を',
      intro: 'まずは下のよくある質問をご覧ください。解決しない場合は、メールまたは GitHub Issues からプロジェクト管理者へ連絡できます。',
      contactEyebrow: 'お問い合わせ', contactTitle: '内容を渡さず、問題だけを伝える',
      contactBody: '端末名、OS の版、当归の版、再現手順、表示されたメッセージをお知らせください。実際の利用データは通常必要ありません。',
      emailCta: 'サポートへメール', issuesCta: 'GitHub Issues を開く', downloadCta: '現在の公開版を見る',
      warningTitle: '送信する前に',
      warningBody: '実際の事項、ノート、データベース、バックアップ、パスワード、証明書、鍵、その他の個人情報をメールや公開 Issue に送らないでください。必要な場合は匿名化した例だけを使用してください。',
      faqEyebrow: 'よくある質問', faqTitle: 'まず確認したい 6 項目',
      faqs: [
        { question: '当归の版はどこで確認できますか？', answer: '「設定 → 当归について」でインストール済みの版を確認できます。サイトの「入手」ページには現在の公開版、公開状態、検証ファイルが表示されます。開発中の版は先に表示されません。' },
        { question: 'バックアップ、復元、書き出しの違いは？', answer: '「設定 → データとバックアップ」を開きます。完全な復元には .dgbak を使い、長期閲覧や移行には Markdown と JSON を含む読みやすい ZIP を作成します。復元前には現在のデータが先に保存されます。信頼できるファイルだけを使ってください。' },
        { question: '通知が鳴らないときは？', answer: '事項カードの通知状態を確認し、システムの通知、音、振動が有効か確かめてください。Android では正確な通知の権限と省電力制限も確認します。iOS の音と振動はシステムの通知設定で管理されます。' },
        { question: '必要な iOS の版は？', answer: '現在のソースビルドには iOS 15 以降と、自分の Apple 署名情報およびプロビジョニングプロファイルが必要です。' },
        { question: 'Android 版は安定版ですか？', answer: 'はい。v1.1.5 は現在推奨される安定版で、Android 7.0 以降向けの正式署名済み universal APK を提供します。導入や更新の前にリリース説明を読み、SHA256SUMS を確認し、大切なデータをバックアップしてください。' },
        { question: 'iPhone に直接インストールできるのはいつですか？', answer: 'iPhone 版は準備中です。現在は App Store、TestFlight、直接インストールできる IPA はありません。「入手」ページと公開 Release が最新状況の基準です。' },
      ],
    },
    footer: { tagline: 'ローカル記録・アップロードなし・AI 不使用', source: 'ソースコード', license: 'Apache 2.0', trademark: 'ブランドと商標', status: '現在の公開版' },
  },
  ru: {
    localeName: 'Русский', shortLocale: 'RU', skipLink: 'Перейти к основному содержанию', brandAria: 'Главная 当归',
    metaDescription: 'Спокойный локальный процесс, связывающий планы, напоминания, действия, Прошлое и Заметки.',
    nav: { features: 'Возможности', stories: 'Истории', download: 'Скачать', privacy: 'Приватность', support: 'Поддержка', github: 'GitHub', menu: 'Меню', language: 'Сменить язык' },
    common: {
      preRelease: 'Публичная предварительная версия', stableRelease: 'Стабильная версия', currentPublicRelease: 'Текущая публичная версия',
      releaseUnavailable: 'Сведения о версии временно недоступны', publishedOn: 'Опубликовано', readStory: 'Прочитать историю',
      viewAllStories: 'Прочитать все восемь историй', backToStories: 'Назад к историям', previousStory: 'Предыдущая', nextStory: 'Следующая', openNewWindow: 'Откроется в новом окне',
    },
    home: {
      promise: 'Локальные записи · Без загрузки · Без ИИ', primaryCta: 'Получить текущую публичную версию', secondaryCta: 'Посмотреть настоящее приложение',
      releaseNote: 'Стабильная версия для Android · для iOS только исходники · статус следует опубликованным GitHub Releases',
      previewEyebrow: 'Настоящий процесс, а не макет', previewTitle: 'От сегодняшнего дня к Прошлому, к которому можно вернуться',
      previewDescription: 'Планы, напоминания, действия, Прошлое и Заметки естественно продолжаются на одном спокойном листе.',
      previewAlt: 'Настоящий рабочий процесс приложения 当归', showcaseCapture: 'Пример реального интерфейса · Снимки из v1.1.5',
      showcaseItems: [
        { title: 'План становится сегодняшним шагом', body: 'Начните с шара и ростка, превратив мысль в одно действие на сегодня.' },
        { title: 'Готово не значит исчезло', body: 'Завершённые действия переходят в редактируемое Прошлое.' },
        { title: 'Запишите и заберите с собой', body: 'Заметки сохраняют мысли, а читаемый экспорт оставляет данные вашими.' },
      ],
      featuresEyebrow: 'Три важные вещи', featuresTitle: 'Помогает помнить, не управляя вашей жизнью',
      storiesEyebrow: 'Бумажный сад 小当归 («маленького Дангуя»)', storiesTitle: 'Пять бумажных страниц для спокойного чтения',
      storiesDescription: 'Наведите указатель, переведите фокус или коснитесь страницы — она выйдет вперёд. Все восемь историй доступны полностью.',
      privacyEyebrow: 'Инструмент должен спокойно принадлежать вам', privacyTitle: 'Ваши слова — не наше сырьё',
      privacyDescription: '当归 не требует аккаунта и не содержит рекламы, аналитики или удалённого ИИ. Записи остаются на устройстве и в выбранных вами копиях.',
      privacyPoints: ['Без аккаунта', 'Без загрузки содержимого', 'Без рекламы и аналитики', 'Без разрешения INTERNET на Android'],
      downloadEyebrow: 'Получить 当归', downloadTitle: 'Публичные версии приходят через один проверенный канал',
      downloadDescription: 'Сайт принимает только опубликованные GitHub Releases с полным набором файлов. Ветки, отдельные теги и черновики скрыты.',
      androidCta: 'Варианты для Android', iosCta: 'Инструкция по сборке iOS',
      sectionNav: { label: 'На этой странице', show: 'Показать навигацию', hide: 'Скрыть навигацию', items: { top: 'Начало', preview: 'Интерфейс', features: 'Возможности', stories: 'Истории', privacy: 'Приватность', download: 'Скачать' } },
    },
    stories: { eyebrow: 'Бумажный сад', title: 'Восемь историй 小当归', intro: 'Это не замена документации, а другой способ почувствовать локальность, тишину и возможность всё исправить.', detailEyebrow: 'История 小当归', relatedTitle: 'Бумага продолжается' },
    download: {
      eyebrow: 'Получить 当归', title: 'Перед загрузкой проверьте текущую публичную версию', intro: 'Версия, канал, дата и файлы автоматически берутся из опубликованного GitHub Release. Разработка не показывается заранее.',
      androidTitle: 'Android', androidBody: 'Большинству нужен официально подписанный универсальный Release APK. Раздельные APK и AAB предназначены для разработчиков.',
      androidRecommended: 'Рекомендуется: danggui-android-universal-release.apk', releaseCta: 'Прочитать полное описание', androidCta: 'Скачать универсальный Android APK',
      checksumTitle: 'Проверка перед установкой', checksumBody: 'Канал содержит SHA256SUMS и отпечаток сертификата подписи. Не устанавливайте неизвестные файлы или debug-fallback.', checksumCta: 'Скачать SHA256SUMS',
      iosTitle: 'iOS', sourceLabel: 'Исходный код', iosBody: 'Для iOS доступны полный исходный код, проект Xcode и свидетельство сборки без подписи. Для устройства нужны собственные данные подписи Apple.',
      iosWarning: 'Это не IPA, и сборки TestFlight нет. Архив исходников нельзя установить прямо на обычный iPhone.',
      iosCta: 'Скачать текущие исходники iOS', iosGuideCta: 'Инструкция по сборке iOS из исходников',
      previewAvailable: 'Также доступна более новая публичная preview-версия', previewCta: 'Открыть preview-версию', allReleasesCta: 'Все публичные версии', beforeTitle: 'Перед началом',
      releaseHighlightsEyebrow: 'Стабильная версия v1.1.5',
      releaseHighlightsTitle: 'Спокойная надёжность в самой основе',
      releaseHighlightsIntro: 'Версия закрывает уязвимые стыки между напоминаниями, часовыми поясами, целостностью базы и восстановлением, не перенося эту сложность в повседневную работу.',
      releaseHighlights: [
        { title: 'Старое действие не меняет новую редакцию', body: 'Stop или Snooze из устаревшего уведомления больше не изменяет напоминание, отредактированное позднее.' },
        { title: 'Напоминания сохраняют часовой пояс', body: 'Первичное расписание и Snooze на 10, 30 или 60 минут сохраняют исходный часовой пояс и учитывают переходы на летнее время.' },
        { title: 'База проверяется полностью', body: 'При запуске и восстановлении выполняются полные проверки целостности и схемы до того, как необычные данные попадут в обычные операции записи.' },
        { title: 'У сбоя остаётся честная граница', body: 'Для пропавших напоминаний используется ограниченное и проверяемое восстановление, а временный открытый текст обмена и восстановления удаляется из точных каталогов.' },
      ],
      evidenceTitle: 'Граница доказательств',
      evidenceBody: 'Стабильная версия означает рекомендуемый канал, но не проверку каждого сценария на физических устройствах. Автоматизация пройдена на Android API 24/36 и в симуляторах iOS 18.5/26.5. Для iOS по-прежнему доступны только исходники — без IPA и TestFlight. Длительная фоновая доставка на устройствах, отдельные OEM и внезапное отключение питания остаются в границах, описанных в примечаниях к выпуску.',
      beforeItems: ['Создайте резервную копию .dgbak перед обновлением важных данных.', 'Убедитесь, что риск текущего канала вам подходит.', 'Не прикладывайте настоящие заметки, копии или пароли к публичным Issue.'],
    },
    privacy: {
      eyebrow: 'Обещание приватности', proofEyebrow: 'Открытый код · Публичный аудит', title: 'Записи остаются на устройстве. Границы видны.', intro: '当归 — полностью локальное приложение для Дел и Заметок. Чтобы начать, не нужно передавать свою жизнь аккаунту.',
      principles: [
        { title: 'Без аккаунта', body: 'Нет входа, профиля пользователя или сервера приложения. Откройте и работайте офлайн.' },
        { title: 'Без загрузки', body: 'Дела, Прошлое и Заметки остаются в песочнице приложения и выбранных локальных копиях.' },
        { title: 'Без запросов к ИИ', body: 'Приложение не отправляет текст ИИ. Только вы решаете, как использовать сделанный экспорт.' },
        { title: 'Без слежения', body: 'Нет рекламы, аналитики, телеметрии сбоев, Firebase и SDK отслеживания.' },
      ],
      policyEyebrow: 'Официальная политика', policyTitle: 'Как данные хранятся, перемещаются и удаляются', policyUpdated: 'Дата вступления в силу: 26 августа 2026 г.',
      controllerTitle: 'Кто предоставляет эту политику',
      controllerBody: 'Эту политику предоставляет сопровождающий проекта 当归. Вопросы о приватности и границах обработки можно отправить на адрес поддержки внизу страницы.',
      policySections: [
        { title: 'Локальные данные на устройстве', body: 'Дела, напоминания, Прошлое, Заметки и настройки хранятся в локальной базе данных и песочнице приложения на устройстве. У сопровождающего проекта нет сервера приложения, который мог бы прочитать это содержимое.' },
        { title: 'Разрешения, экспорт и удаление', body: 'Напоминания запрашивают системное разрешение на уведомления только при необходимости. Копии и читаемый экспорт создаются лишь по вашей команде в выбранном месте. Записи можно удалить в приложении, само приложение — удалить с устройства, а экспортированные файлы — стереть самостоятельно.' },
        { title: 'Чего приложение не делает', body: 'Приложение не создаёт аккаунт, не хранит содержимое в облаке проекта, не использует рекламу, аналитику посещений, телеметрию сбоев или удалённый ИИ и не загружает записи автоматически.' },
        { title: 'Письма в поддержку', body: 'Отправленные адрес и текст письма используются только для понимания запроса и ответа. Они удаляются после решения вопроса и завершения необходимого срока хранения в целях безопасности. Не отправляйте настоящие заметки, копии, пароли, сертификаты и другие приватные данные.' },
        { title: 'Сайт и внешние ссылки', body: 'На сайте нет аккаунтов, форм и аналитики посетителей. Cloudflare обрабатывает необходимые метаданные соединения — например IP-адрес, время запроса, URL и сведения о браузере — для доставки, защиты и работы сайта. После перехода на GitHub действует собственная политика приватности GitHub.' },
      ],
      proofTitle: 'Обещание можно проверить', proofBody: 'Финальный манифест Android не объявляет разрешение INTERNET. В iOS нет Push, CloudKit или фоновой сети. Зависимости и настройки публично проверены.',
      proofCta: 'Открыть текущий аудит приватности', siteTitle: 'Об этом сайте',
      siteBody: 'Сервер сайта читает только публичный манифест выпуска и не может получить доступ к вашим записям 当归. По вопросам приватности и данных можно напрямую написать сопровождающему проекта.',
      contactCta: 'Написать о приватности',
    },
    support: {
      eyebrow: 'Поддержка пользователей', title: 'Спокойный путь назад, когда что-то не работает',
      intro: 'Сначала проверьте ответы ниже. Если решения нет, напишите сопровождающему проекта по электронной почте или через GitHub Issues.',
      contactEyebrow: 'Связаться', contactTitle: 'Опишите проблему, не раскрывая содержимое',
      contactBody: 'Укажите модель устройства, версию системы, версию 当归, шаги воспроизведения и показанное сообщение. Настоящие пользовательские данные почти никогда не нужны.',
      emailCta: 'Написать в поддержку', issuesCta: 'Открыть GitHub Issues', downloadCta: 'Текущая публичная версия',
      warningTitle: 'Перед отправкой',
      warningBody: 'Не отправляйте по почте или в публичный Issue настоящие дела, заметки, базы данных, резервные копии, пароли, сертификаты, ключи и другие личные сведения. При необходимости используйте обезличенный пример.',
      faqEyebrow: 'Частые вопросы', faqTitle: 'Сначала проверьте эти 6 пунктов',
      faqs: [
        { question: 'Где посмотреть версию 当归?', answer: 'Откройте «Настройки → О 当归», чтобы увидеть установленную версию. На странице «Скачать» показаны текущая публичная версия, канал и файлы проверки. Разрабатываемые версии не появляются заранее.' },
        { question: 'Чем отличаются копия, восстановление и экспорт?', answer: 'Откройте «Настройки → Данные и резервные копии». Для полного восстановления используйте .dgbak. Для долгого чтения или переноса создайте читаемый ZIP с Markdown и JSON. Перед восстановлением 当归 сохраняет текущие данные; используйте только доверенные файлы.' },
        { question: 'Что проверить, если напоминание не прозвучало?', answer: 'Проверьте состояние напоминания на карточке дела, затем системные уведомления, звук и вибрацию. На Android также проверьте разрешение точных напоминаний и ограничения энергосбережения. На iOS звуком и вибрацией управляют системные настройки уведомлений.' },
        { question: 'Какая версия iOS требуется?', answer: 'Для текущей сборки из исходников нужна iOS 15 или новее, а также ваши данные подписи Apple и профиль подготовки.' },
        { question: 'Версия Android уже стабильна?', answer: 'Да. v1.1.5 — текущая рекомендуемая стабильная версия с официально подписанным универсальным APK для Android 7.0+. Перед установкой или обновлением прочитайте описание выпуска, проверьте SHA256SUMS и сохраните копию важных данных.' },
        { question: 'Когда 当归 можно будет установить на iPhone?', answer: 'Версия для iPhone готовится. Сейчас нет страницы в App Store, сборки TestFlight или IPA для прямой установки. Актуальный статус указан на странице «Скачать» и в опубликованных Releases.' },
      ],
    },
    footer: { tagline: 'Локальные записи · Без загрузки · Без ИИ', source: 'Исходный код', license: 'Apache 2.0', trademark: 'Бренд и товарные знаки', status: 'Текущая публичная версия' },
  },
};
