import 'package:drift/native.dart';

import 'database.dart';

/// Rejects backups whose physical schema is not the exact schema generated by
/// this build. `user_version` alone does not exclude attacker-controlled
/// triggers, views, missing columns, altered constraints, or missing indexes.
final class DangguiSchemaVerifier {
  const DangguiSchemaVerifier._();

  static Future<List<String>>? _expectedRows;

  static Future<void> verify(DangguiDatabase database) async {
    final expected = await (_expectedRows ??= _loadExpectedRows());
    final actual = await _schemaRows(database);
    if (!_sameRows(expected, actual)) {
      throw const FormatException('Backup database schema does not match.');
    }
  }

  static Future<List<String>> _loadExpectedRows() async {
    final database = DangguiDatabase(NativeDatabase.memory());
    try {
      await database.customSelect('SELECT 1').getSingle();
      return await _schemaRows(database);
    } finally {
      await database.close();
    }
  }

  static Future<List<String>> _schemaRows(DangguiDatabase database) async {
    final rows = await database
        .customSelect(
          "SELECT type, name, tbl_name, sql FROM sqlite_schema "
          "WHERE type IN ('table', 'index', 'view', 'trigger') "
          "AND name NOT LIKE 'sqlite_%' ORDER BY type, name",
        )
        .get();
    return rows
        .map(
          (row) => <String>[
            row.read<String>('type'),
            row.read<String>('name'),
            row.read<String>('tbl_name'),
            _canonicalSql(row.data['sql']),
          ].join('\u001f'),
        )
        .toList(growable: false);
  }

  static String _canonicalSql(Object? value) {
    if (value == null) return '<null>';
    return value.toString().replaceAll(RegExp(r'\s+'), ' ').trim();
  }

  static bool _sameRows(List<String> expected, List<String> actual) {
    if (expected.length != actual.length) return false;
    for (var index = 0; index < expected.length; index++) {
      if (expected[index] != actual[index]) return false;
    }
    return true;
  }
}
